#define RGFW_IMPLEMENTATION
#define RGFW_OPENGL
#define NANOVG_GL3_IMPLEMENTATION

#include "shared.h"

#define STB_IMAGE_IMPLEMENTATION
#include "stb/stb_image.h"

#define FONTSTASH_IMPLEMENTATION
#include "nanovgXC/fontstash.h"

#ifdef _WIN32
#include <windows.h>
#endif

#include <stdio.h>

// This file is generated by the build system (nob.c)
#include "font.h" 

// Include module implementations (header-only style for this refactor)
#include "pngtuber.h"
#include "menu.h"
#include "settings.h"
#include "dialog.h"

// Define globals declared in shared.h
RGFW_window* win = NULL;
RGFW_window* menu = NULL;
RGFW_window* settings = NULL;
RGFW_window* dialog = NULL;

NVGcontext* vg_win = NULL;
NVGcontext* vg_menu = NULL;
NVGcontext* vg_settings = NULL;
NVGcontext* vg_dialog = NULL;

int running = 1;

int main() {
    // Initialize Main Window (PNGTuber)
    pngtuber_init();
    if (!win) return 1;

    while (running && RGFW_window_shouldClose(win) == RGFW_FALSE) {
        RGFW_pollEvents();

        RGFW_event event;
        
        // Handle Main Window Events
        while (RGFW_window_checkQueuedEvent(win, &event)) {
            pngtuber_handle_event(&event);
        }

        // Handle Menu Events
        if (menu) {
            while (menu && RGFW_window_checkQueuedEvent(menu, &event)) {
                menu_handle_event(&event);
            }
        }

        // Handle Settings Events
        if (settings) {
            while (settings && RGFW_window_checkQueuedEvent(settings, &event)) {
                settings_handle_event(&event);
            }
        }

        // Handle Dialog Events
        if (dialog) {
            while (dialog && RGFW_window_checkQueuedEvent(dialog, &event)) {
                dialog_handle_event(&event);
            }
        }

        // Rendering
        pngtuber_draw();
        menu_draw();
        settings_draw();
        dialog_draw();
    }

    // Cleanup
    if (menu) { 
        RGFW_window_makeCurrentContext_OpenGL(menu); 
        if (vg_menu) nvglDelete(vg_menu); 
        RGFW_window_close(menu); 
    }
    if (settings) { 
        RGFW_window_makeCurrentContext_OpenGL(settings); 
        if (vg_settings) nvglDelete(vg_settings); 
        RGFW_window_close(settings); 
    }
    if (dialog) { 
        RGFW_window_makeCurrentContext_OpenGL(dialog); 
        if (vg_dialog) nvglDelete(vg_dialog); 
        RGFW_window_close(dialog); 
    }
    
    if (win) {
        RGFW_window_makeCurrentContext_OpenGL(win);
        if (vg_win) nvglDelete(vg_win);
        RGFW_window_close(win);
    }
    
    return 0;
}